version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ditotasker_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ditotasker_pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: ditotasker_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"

  sidekiq:
    build: .
    container_name: ditotasker_sidekiq
    depends_on:
      - redis
      - postgres
    command: bundle exec sidekiq
    env_file:
      - .env
    environment:
      REDIS_URL: redis://ditotasker_redis:6380/0
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data:
  redis_data:
