default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWD'] || 'postgres' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: ditotasker_development

test:
  <<: *default
  database: ditotasker_test

production:
  <<: *default
  database: ditotasker_production
  username: <%= ENV['PROD_POSTGRES_USER'] %>
  password: <%= ENV['PROD_POSTGRES_PASSWD'] %>
  host: <%= ENV['PROD_POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['PROD_POSTGRES_PORT'] || '5432' %>
